# Generated by Django 3.0 on 2019-12-19 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('principal', models.PositiveIntegerField()),
                ('effective_annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('term', models.PositiveIntegerField(help_text='Total term of the loan, in years')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
