# Generated by Django 3.0 on 2019-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weekly_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_years', models.PositiveIntegerField()),
            ],
        ),
    ]
